name: Tuist CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      # 1. Check out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set the correct Xcode version
      - name: Select Xcode 16.2.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'

      # 3. Install Mise and Tuist
      - name: Setup Mise and Tuist
        uses: jdx/mise-action@v2

      # 4. Run Tuist install
      - name: Install dependencies
        run: tuist install
        env:
          TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_TOKEN}}

      # 5. Create API key file for build
      - name: Create GenerativeAI-Info.plist
        run: |
          mkdir -p Nemo/Resources
          cat > Nemo/Resources/GenerativeAI-Info.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>API_KEY</key>
              <string>dummy-api-key-for-ci</string>
          </dict>
          </plist>
          EOF

      # 6. Clear cache and build with xcodebuild directly
      - name: Build project (bypass Tuist build)
        run: |
          # Clear any cached destinations that might be causing issues
          rm -rf ~/.tuist
          rm -rf .tuist
          
          # Generate the project fresh
          tuist clean
          tuist install
          tuist generate
          
          # Build with generic simulator destination using xcodebuild directly
          echo "Building with xcodebuild and generic destination..."
          xcodebuild build \
            -workspace Nemo.xcworkspace \
            -scheme Nemo \
            -destination "generic/platform=iOS Simulator" \
            CODE_SIGNING_ALLOWED=NO
            
        env:
          TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_TOKEN}}
