# .github/workflows/tuist.yml

name: Tuist CI (macOS-15 with platform install)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: macos-latest  # This now uses macOS-15
    steps:
      # 1. Check out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set the correct Xcode version
      - name: Select Xcode 16.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      # 3. Install iOS platform manually (as suggested in GitHub issue)
      - name: Install iOS platform
        run: |
          echo "Installing iOS platform to fix simulator issues..."
          xcodebuild -downloadPlatform iOS
          
          # List available simulators to verify
          xcrun simctl list devices available

      # 4. Install Mise and Tuist
      - name: Setup Mise and Tuist
        uses: jdx/mise-action@v2

      # 5. Run Tuist install
      - name: Install dependencies
        run: tuist install
        env:
          TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_TOKEN}}

      # 6. Build with Tuist
      - name: Build project
        run: tuist build
        env:
          TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_TOKEN}}
