name: Tuist CI (macOS-15 with platform install)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      # Add a step to create the missing plist file for CI
      - name: Create GenerativeAI-Info.plist for CI
        run: |
          cat > Nemo/Resources/GenerativeAI-Info.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>API_KEY</key>
              <string>dummy_key_for_ci</string>
          </dict>
          </plist>
          EOF

      # Try without the iOS platform download step first
      - name: Setup Mise and Tuist
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: tuist install
        env:
          TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_TOKEN}}

      - name: Build project
        run: tuist build
        env:
          TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_TOKEN}}
